### ISSUE TITLE
Need Some assistance related to youtube Channel App

### ISSUE THREAD

**Issue by rajesh-h** [JoxieMedina/ionic2-simple-conditional-wizard#6]
Apologies I am raising issue here for this Ionic2-Angular2-YouTube-Channel-App [repo](https://github.com/JoxieMedina/Ionic2-Angular2-YouTube-Channel-App)  , as  I could not raise the issue on that repo.

This is not an issue but a small help.

As you are aware currenlty the app shows video on top of the home.html page, I would like to show the video on a new page called details.html when clicked on play button on home.html

Could you please help me how i can achieve this, a small guidance should help me to start off, I tried my best to modify code but for no avail. 

Once again apologies for posting the issue here.

**Comment by JoxieMedina** [comment]
Hi there,
Just pass the player header to details template, and in the method playVideo() push the details page with the object `post`as param of the detail page, then you can use the this.ytPlayer.launchPlayer(post.id, post.snippet.title) method in the detail page.

**Comment by rajesh-h** [comment]
@JoxieMedina  Thank you very much for coming back to me. Infact I tried to contact original developer of this app, he/she did not respond. Thanks a lot for your assistance.

Unfortunately I am not successful as of now.

This is my detail.ts
https://github.com/just10minutes/MyYouTubeChannelIonic2App/blob/master/pages/details/details.ts

Probably if you check this file you might find what I am doing wrong.

On details.html file I have added another play button but I would like to have it auto played on details.html when I click play button on home.html

For now when i click play button on details.html i get below error.

`Runtime Error
Error in ./DetailsPage class DetailsPage - caused by: this.youtube.player.loadVideoById is not a function`

`TypeError: this.youtube.player.loadVideoById is not a function
    at YoutubeService.launchPlayer (http://localhost:8100/build/main.js:56858:29)
    at DetailsPage.playVideo (http://localhost:8100/build/main.js:83039:23)
    at CompiledTemplate.proxyViewClass.View_DetailsPage0.handleEvent_21 (/AppModule/DetailsPage/component.ngfactory.js:244:34)
    at CompiledTemplate.proxyViewClass.<anonymous> (http://localhost:8100/build/main.js:112244:37)
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/main.js:56186:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10284)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:36740:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10220)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7637)
    at HTMLButtonElement.invoke (http://localhost:8100/build/polyfills.js:3:11397)`

**Comment by rajesh-h** [comment]
@JoxieMedina  I believe based on the error it looks like my player is not loaded on the details.html page. But not sure how to make it load. 
Even home.html does not have any special method which makes the player to be ready to play the video.

Your assistance will help me a lot in sorting this issue.

**Comment by JoxieMedina** [comment]
Hi There, I'm gonna close this issue and I'll provide my support through Skype or hangout, contact me at josuelp17@gmail.com
